// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: queque.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TestId  int64  `protobuf:"varint,1,opt,name=testId,proto3" json:"testId,omitempty"`
	TestStr string `protobuf:"bytes,2,opt,name=testStr,proto3" json:"testStr,omitempty"`
}

func (x *TestReq) Reset() {
	*x = TestReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queque_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestReq) ProtoMessage() {}

func (x *TestReq) ProtoReflect() protoreflect.Message {
	mi := &file_queque_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestReq.ProtoReflect.Descriptor instead.
func (*TestReq) Descriptor() ([]byte, []int) {
	return file_queque_proto_rawDescGZIP(), []int{0}
}

func (x *TestReq) GetTestId() int64 {
	if x != nil {
		return x.TestId
	}
	return 0
}

func (x *TestReq) GetTestStr() string {
	if x != nil {
		return x.TestStr
	}
	return ""
}

type TestResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack int64 `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (x *TestResp) Reset() {
	*x = TestResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queque_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResp) ProtoMessage() {}

func (x *TestResp) ProtoReflect() protoreflect.Message {
	mi := &file_queque_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResp.ProtoReflect.Descriptor instead.
func (*TestResp) Descriptor() ([]byte, []int) {
	return file_queque_proto_rawDescGZIP(), []int{1}
}

func (x *TestResp) GetAck() int64 {
	if x != nil {
		return x.Ack
	}
	return 0
}

type TestDelayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TestId  int64  `protobuf:"varint,1,opt,name=testId,proto3" json:"testId,omitempty"`
	TestStr string `protobuf:"bytes,2,opt,name=testStr,proto3" json:"testStr,omitempty"`
	Time    int64  `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *TestDelayReq) Reset() {
	*x = TestDelayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queque_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestDelayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestDelayReq) ProtoMessage() {}

func (x *TestDelayReq) ProtoReflect() protoreflect.Message {
	mi := &file_queque_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestDelayReq.ProtoReflect.Descriptor instead.
func (*TestDelayReq) Descriptor() ([]byte, []int) {
	return file_queque_proto_rawDescGZIP(), []int{2}
}

func (x *TestDelayReq) GetTestId() int64 {
	if x != nil {
		return x.TestId
	}
	return 0
}

func (x *TestDelayReq) GetTestStr() string {
	if x != nil {
		return x.TestStr
	}
	return ""
}

func (x *TestDelayReq) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type TestDelayResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack int64 `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (x *TestDelayResp) Reset() {
	*x = TestDelayResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queque_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestDelayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestDelayResp) ProtoMessage() {}

func (x *TestDelayResp) ProtoReflect() protoreflect.Message {
	mi := &file_queque_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestDelayResp.ProtoReflect.Descriptor instead.
func (*TestDelayResp) Descriptor() ([]byte, []int) {
	return file_queque_proto_rawDescGZIP(), []int{3}
}

func (x *TestDelayResp) GetAck() int64 {
	if x != nil {
		return x.Ack
	}
	return 0
}

var File_queque_proto protoreflect.FileDescriptor

var file_queque_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x71, 0x75, 0x65, 0x71, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x3b, 0x0a, 0x07, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x65, 0x73, 0x74, 0x53, 0x74, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x65, 0x73, 0x74, 0x53, 0x74, 0x72, 0x22,
	0x1c, 0x0a, 0x08, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x22, 0x54, 0x0a,
	0x0c, 0x54, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x65, 0x73, 0x74, 0x53, 0x74, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x65, 0x73, 0x74, 0x53, 0x74, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x22, 0x21, 0x0a, 0x0d, 0x54, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x61, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x32, 0x61, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12,
	0x26, 0x0a, 0x09, 0x54, 0x65, 0x73, 0x74, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x0b, 0x2e, 0x70,
	0x62, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x54,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x09, 0x54, 0x65, 0x73, 0x74, 0x44,
	0x65, 0x6c, 0x61, 0x79, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x44, 0x65,
	0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x65, 0x73, 0x74,
	0x44, 0x65, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_queque_proto_rawDescOnce sync.Once
	file_queque_proto_rawDescData = file_queque_proto_rawDesc
)

func file_queque_proto_rawDescGZIP() []byte {
	file_queque_proto_rawDescOnce.Do(func() {
		file_queque_proto_rawDescData = protoimpl.X.CompressGZIP(file_queque_proto_rawDescData)
	})
	return file_queque_proto_rawDescData
}

var file_queque_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_queque_proto_goTypes = []interface{}{
	(*TestReq)(nil),       // 0: pb.TestReq
	(*TestResp)(nil),      // 1: pb.TestResp
	(*TestDelayReq)(nil),  // 2: pb.TestDelayReq
	(*TestDelayResp)(nil), // 3: pb.TestDelayResp
}
var file_queque_proto_depIdxs = []int32{
	0, // 0: pb.Queue.TestQueue:input_type -> pb.TestReq
	2, // 1: pb.Queue.TestDelay:input_type -> pb.TestDelayReq
	1, // 2: pb.Queue.TestQueue:output_type -> pb.TestResp
	3, // 3: pb.Queue.TestDelay:output_type -> pb.TestDelayResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_queque_proto_init() }
func file_queque_proto_init() {
	if File_queque_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_queque_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queque_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queque_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestDelayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queque_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestDelayResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_queque_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_queque_proto_goTypes,
		DependencyIndexes: file_queque_proto_depIdxs,
		MessageInfos:      file_queque_proto_msgTypes,
	}.Build()
	File_queque_proto = out.File
	file_queque_proto_rawDesc = nil
	file_queque_proto_goTypes = nil
	file_queque_proto_depIdxs = nil
}
