// Code generated by goctl. DO NOT EDIT.
// Source: queque.proto

package server

import (
	"context"

	"rabbitmq-demo/test/internal/logic"
	"rabbitmq-demo/test/internal/svc"
	"rabbitmq-demo/test/pb"
)

type QueueServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedQueueServer
}

func NewQueueServer(svcCtx *svc.ServiceContext) *QueueServer {
	return &QueueServer{
		svcCtx: svcCtx,
	}
}

// 创建消息队列
func (s *QueueServer) TestQueue(ctx context.Context, in *pb.TestReq) (*pb.TestResp, error) {
	l := logic.NewTestQueueLogic(ctx, s.svcCtx)
	return l.TestQueue(in)
}

// 延迟队列
func (s *QueueServer) TestDelay(ctx context.Context, in *pb.TestDelayReq) (*pb.TestDelayResp, error) {
	l := logic.NewTestDelayLogic(ctx, s.svcCtx)
	return l.TestDelay(in)
}
